### ISSUE TITLE
Cannot use byte[] in RCFile scheme for Hive binary type

### ISSUE THREAD

**Issue by 4ndypanda** [branky/cascading.hive#12]
The Java type for the binary type in Hive is supposed to be byte[] according to the object inspector. However, when providing a byte[] object in the tuple, the RCFile scheme first casts the object to a string and then to an array of bytes when [sinking the field](https://github.com/branky/cascading.hive/blob/master/src/main/java/cascading/hive/RCFile.java#L252). This is an issue since the toString() call for a byte[] is not the actual contents of byte[].

Is there another way around this issue or do we have to make an exception for a byte[] object in the RCFile code?

**Comment by branky** [comment]
This is a good catch. If you could send a pull request with a patch that would be great!

**Comment by 4ndypanda** [comment]
I will make a pull request to resolve this. Essentially we need to add the following

``` java
if (field instanceof byte[]) {
  out.write(Base64.encodeBase64((byte[]) field));
}
```

to the sinkField method in RCFile.

**Comment by branky** [comment]
@4ndypanda , thank you for your contribution!
