### ISSUE TITLE
cascading-hive does not write yo hcatalog in parquet format.

### ISSUE THREAD

**Issue by btrofimov** [branky/cascading.hive#3]
Trying to write data through hcatalog in parquet format I see this exception from hadoop logs [below]. Could you please point out what is going on wrong ? I use cascading-hive of latest master version (just built when you said about parquet support). Code which I use is extrimely simple - just read data from one table and put it to another with parquet aboard.

Thanks in advace and best regards,
Boris

Error: java.lang.RuntimeException: Should never be used at parquet.hive.DeprecatedParquetOutputFormat.getRecordWriter(DeprecatedParquetOutputFormat.java:74) at org.apache.hadoop.mapred.MapTask$DirectMapOutputCollector.init(MapTask.java:799) at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:422) at org.apache.hadoop.mapred.MapTask.run(MapTask.java:340) at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:160) at java.security.AccessController.doPrivileged(Native Method) at javax.security.auth.Subject.doAs(Subject.java:396) at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1438) at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:155) Container killed by the ApplicationMaster. Container killed on request. Exit code is 143

**Comment by branky** [comment]
This is an issue about parquet.hive.DeprecatedParquetOutputFormat. It doesn't allow us create record writer from it. I have created another branch with a patch for DeprecatedParquetOutputFormat, which will enable you writing parquet through HCatalog in a Cascading app.  Please checkout https://github.com/branky/cascading.hive/tree/parquet, and build a jar by yourself.

**Comment by btrofimov** [comment]
@branky  - you mentioned  about new jar. Do you mean cascading-hive.jar?  I just replaced jar with new one launch it and see the same error. Do I need update parqiet-mir, where DeprecatedParquetOutputFormat lives? or I have to change reference to OutputParquetFormat when defining table's schema? Please advice and thanks in advance.

Regards,
Boris

**Comment by branky** [comment]
You don't have to update parquet-mr either change the table definition. Did you check out branch "parquet" and rebuild the jar?

**Comment by btrofimov** [comment]
yes, that is what I did, then I just repalced old jar with new version and launched my app. The same result :(

**Comment by branky** [comment]
How did you build the jar? A fat jar with all dependencies? I guess it is. Then the reason might be you also have parquet dependency there. 
From the error stack, seems still using original parquet.hive.DeprecatedParquetOutputFormat. You can remove parquet dependency because cascading.hive already includes parquet-hive-bundle
and DeprecatedParquetOutputFormat is patched to allow creating record writor .
