### ISSUE TITLE
Using cascading.hive with Scalding

### ISSUE THREAD

**Issue by hellertime** [branky/cascading.hive#4]
I am making use of cascading.hive with scalding. To do so I created some new classes derived from the SchemedSource object in scalding.

They may be of use to others, so I wanted to share them.

https://gist.github.com/hellertime/10020639

I'm happy to make a pull request with the changes, but wasn't sure how best to integrate the code, so I would appreciate some feedback in that regard before I begin.

-Chris

**Comment by branky** [comment]
Thanks for sharing. Your gist looks good to me. If it worked well for you, feel free to make a pull request.
